### ISSUE TITLE
9주차 문제(Week 9 Assignments)

### ISSUE THREAD

**Issue by Queue-ri** [Queue-ri/Advanced-Algorithm-Study#108]
# 9주차 문제(Week 9 Assignments)
마감(Deadline): 2021/03/14 10:00

## 필수문제(Mandatory)
Link | Problem | Difficulty
----- | --------- | :-------:
[ALLERGY](http://algospot.com/judge/problem/read/ALLERGY)  | 알러지가 심한 친구들 | ![](https://img.shields.io/badge/-intermediate-yellow)
[ARCTIC](http://algospot.com/judge/problem/read/ARCTIC)  | 남극 기지 | ![](https://img.shields.io/badge/-easy-brightgreen)
[CANADATRIP](http://algospot.com/judge/problem/read/CANADATRIP) | 캐나다 여행 | ![](https://img.shields.io/badge/-intermediate-yellow)

## 선택문제(Optional)
Link | Problem | Difficulty
----- | --------- | :-------:
[KAKURO2](http://algospot.com/judge/problem/read/KAKURO2) | 카쿠로 | ![](https://img.shields.io/badge/-intermediate-yellow)
[DARPA](http://algospot.com/judge/problem/read/DARPA) | DARPA Grand Challenge | ![](https://img.shields.io/badge/-intermediate-yellow)

**Comment by yujungee** [comment]
확인 완료
