### ISSUE TITLE
10주차 문제(Week 10 Assignments)

### ISSUE THREAD

**Issue by Queue-ri** [Queue-ri/Advanced-Algorithm-Study#109]
# 10주차 문제(Week 10 Assignments)
마감(Deadline): 2021/03/28 10:00

## 필수문제(Mandatory)
Link | Problem | Difficulty
----- | --------- | :-------:
[RATIO](http://algospot.com/judge/problem/read/RATIO)  | 승률 올리기 | ![](https://img.shields.io/badge/-easy-brightgreen)
[PASS486](http://algospot.com/judge/problem/read/PASS486)  | 비밀번호 486 | ![](https://img.shields.io/badge/-intermediate-yellow)
[NERDS](http://algospot.com/judge/problem/read/NERDS) | 너드인가, 너드가 아닌가? | ![](https://img.shields.io/badge/-intermediate-yellow)

**Comment by Yunhyunjo** [comment]
확인 완료

**Comment by hanjuuuuuu** [comment]
확인 완료

**Comment by yujungee** [comment]
확인 완료
