### ISSUE TITLE
[Week 2] TRIPATHCNT self review - profitjean

### ISSUE THREAD

**Issue by profitjean** [Queue-ri/Advanced-Algorithm-Study#133]
# TRIPATHCNT self review ![](https://img.shields.io/badge/-TLE-%2300346b)

## 1. 해결 시도 과정
최대 경로를 구하는 동시에 최대 경로의 가능 개수를 구해서 출력해야하는 것이 문제의 포인트였다.
## 2. 작성한 코드와 설명
```py
import sys
case = int(sys.stdin.readline().rstrip())
for _ in range(case):
    n = int(sys.stdin.readline().rstrip())
    triangle = [list(map(int, sys.stdin.readline().rstrip().split())) for _ in range(n)]

    memo = dict()
    def path(y,x):
        if y == n -1:
            return triangle[y][x]
        if (x,y) not in memo:
            memo[(y,x)] = max(path(y+1,x), path(y+1,x+1)) + triangle[y][x]
        return memo[(y,x)]

    memo2 = dict()
    def count(y,x):
        if y == n -1:
            return 1
        if (y,x) not in memo2:
            result = 0
            if path(y+1,x) >= path(y+1,x+1):
                result += count(y+1,x)
            if path(y+1,x+1) >= path(y+1,x):
                result += count(y+1,x+1)
            memo2[(y,x)] = result
        return memo2[(y,x)]
    path(0,0)
    print(count(0,0))
```
최대 경로를 구하는 함수 path와 경로의 개수를 구하는 함수 count를 지정해서 해결해보고자 했다.
path함수 내에서는 max와 재귀함수를 활용해 최댓값을 갱신하고자 했다.
count함수 내에서는 삼각형 내에서 바로아래의 최대 경로값이 큰지, 아래에서 오른쪽의 최대 경로값이 큰지 비교해서 경로를 비교하고자 했다.

## 3. 막힌 점 및 개선 사항
테스트 케이스로 돌려봤을때 문제가 없었는데 알고스팟에서 돌려보니 계속 시간초과가 났다.
시간초과 문제를 해결하는 기본적인 방법인 input()에서 sys.stdin.readline()으로도 변경해보았지만 해결되지 않았다.

**Comment by Queue-ri** [comment]
메모이제이션 테이블을 dictionary로 구현하셨는데 이렇게 하면 매번 if문으로 (y,x)가 테이블에 있는지 in으로 검사할 때마다 O(N)의 시간복잡도가 들어서 비효율적입니다.

대신 functools의 lru_cache를 적절히 사용하시면 통과될겁니다 :)
