### ISSUE TITLE
[Week 2] PACKING self review - profitjean

### ISSUE THREAD

**Issue by profitjean** [Queue-ri/Advanced-Algorithm-Study#135]
# PACKING self review ![](https://img.shields.io/badge/-RTE-%23940000)

## 1. 해결 시도 과정
재귀함수와 반복문을 이용하여 가방에 넣을 수 있는 조합을 찾으려고 했습니다. 기존의 가방문제에 해당 아이템과 개수까지 출력해야하는 조건을 찾아야했기 때문에 재귀함수에서 해당 아이템을 선택할 경우 답안을 출력용으로 만들어둔 빈 리스트에 append시키는 방법을 생각했습니다.

## 2. 작성한 코드와 설명
```py
import sys
case = int(sys.stdin.readline().rstrip())

def reconstruct(n, w, choose):
    if n == N:
        return
    if bag[n][w] == bag[n+1][w]: # 아이템 선택 X
        return reconstruct(n+1, w, choose)
    else:
        choose.append(items[n][0]) # 아이템 선택
        reconstruct(n+1, w-items[n][1], choose)

for _ in range(case):
    N, W = map(int, sys.stdin.readline().rstrip().split())
    items = [None] * N
    bag = [[0]*(W+1) for _ in range (N+1)]
    choose = []
    for j in range(N):
        i = sys.stdin.readline().rstrip().split()
        items[j] = [i[0], int(i[1]), int(i[2])] # 물품명, 사이즈, 우선순위
   # 가방에 담을 수 있는 최대의 무게를 계산하기
    for i in range(1,N+1):
        for j in range(1,W+1):
            w = items[i][1]
            v = items[i][2]
            if j < w:
                bag[i][j] = bag[i-1][j]
            else:
                bag[i][j] = max(bag[i-1][j], bag[i-1][j-w]+v)

    reconstruct(0,W,choose)
    print(bag[N][W], len(choose))
    for name in choose:
        print(name)
```
for문에서 가방에 담을 수 있는 최대의 무게를 계산한 뒤, 재귀함수 reconstruct에서 어떤 아이템들이 들어가있는지 빈 배열 choose에 저장하도록 했습니다.

## 3. 막힌 점 및 개선 사항
최대 무게를 계산하는 부분도 재귀함수로 빼서 풀어보는 것도 좋을 것 같고, 백준문제를 풀어봤지만 다시 풀이를 살펴보니 문제 이해가 다시 필요해보입니다..반복문 내에서 index 범위를 잘못 지정한것같아요.

**Comment by Queue-ri** [comment]
일단 인덱스 문제가 맞고요, RTE 부터 고치자면 `items` 크기와
```diff py
- for j in range(N):
        i = sys.stdin.readline().rstrip().split()
        items[j] = [i[0], int(i[1]), int(i[2])] # 물품명, 사이즈, 우선순위
```
여기 있는 range가 N이 아닌 N+1이 되어야 합니다. 왜냐하면 현재 `# 가방에 담을 수 있는 최대의 무게를 계산하기` 주석 밑에 있는 i가 1~N까지 돌고 있기 때문입니다.

또한 reconstruct 추적 로직도 잘못되었는데, 지금 `if bag[n][w] == bag[n+1][w]:` 이 부분에서 n, n+1을 비교하는 것이 아니라 n, n-1을 비교하는 로직이 되어야 합니다. n번째 물건도 담았는지 확인해줘야 하는데 현재의 reconstruct로는 n번째 물건의 처리를 못하고 있네요. 이 때 추적방향은 거꾸로 가서 0일때가 base case여야 합니다.

그리고 로직을 다 수정하면 아직 TLE가 날텐데, 이건 [채희님 피드백](https://github.com/Queue-ri/Advanced-Algorithm-Study/issues/131#issuecomment-1030627223)과 마찬가지로 **main 함수를 만드셔서 지역으로 코드를 넣어주시면** 통과됩니다.
