### ISSUE TITLE
[Week 3] PI debug review - dakyommii

### ISSUE THREAD

**Issue by Queue-ri** [Queue-ri/Advanced-Algorithm-Study#54]
***
- Related to :  #49
***
@dakyommii 님 PI 코드 디버깅 해드렸습니다.

난이도 계산 로직을 약간 바꿔드린것 말고는 가급적 원본 스타일을 유지하려 했고,

일단 RTE의 주요 원인은 이것 때문이었습니다.
```cpp
int split(string &strS, int idx, int splitNum) {  //파라미터: 입력받은 문자열, 분할 지점
	//int splitNum = 3;

	//splitNum개로 자른 문자열
	string splitStr = strS.substr(idx, splitNum);

	if (idx < strS.length() - splitNum) {  //자르기 가능한지 확인
		...
```
자르기 가능한지 확인하기 전에 이미 `substr`로 자르고 있네요.

그 외에도 여러가지 수정사항이 있었습니다. diffchecker 결과에 모두 나와있지만 몇가지 따로 피드백 드리자면
- 이전 단계로 돌아가는 방법? -> 호출된 재귀함수가 return 하면 그 함수를 호출했던 이전의 함수로 돌아갑니다.
- 이 문제는 레벨을 더해나가면서 호출하기보단, 일단 호출해서 역순으로 더해나가는게 일반적이고 더 효율적입니다.
- 난이도 계산에서 조건문으로 필터링하고 해당 난이도 조건에 중도 어긋날 경우 바로 `return 10;` 하셨는데, 필터링을 하지 않고 return 대신 break 해서 나머지 조건을 마저 체크하는 로직으로 짜는게 더 효율적입니다.
- `문자열 3,4,5개씩 잘라서 레벨 계산` (80~105줄) 하는 부분은 코드 변경사항이 잘 보여야 할 것 같아서 일부러 for문으로 묶지 않았습니다. 간단하니 직접 묶어보세요😉

하단 확인하시고 정리해서 PR 남겨주시기 바랍니다 :)

비교하기 편하시라고 `*** DIFFCHECK 구분선 ***` 주석을 따로 넣었는데 나중에 정리할 땐 지우셔도 돼요~

https://www.diffchecker.com/9lJSXRaa

**Comment by dakyommii** [comment]
확인했습니다. 수정해서 PR 올리겠습니다 감사합니다!
